// <auto-generated />
namespace HR_Management.Context.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class UserCartChanges : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UserCartChanges));
        
        string IMigrationMetadata.Id
        {
            get { return "201612300824413_UserCartChanges"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
