// <auto-generated />
namespace HR_Management.Context.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class UserOrderANdDetails : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UserOrderANdDetails));
        
        string IMigrationMetadata.Id
        {
            get { return "201701021040194_UserOrderANdDetails"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
